### ISSUE TITLE
Customized version

### ISSUE THREAD

**Issue by JorgeAtPaladin** [floitsch/syntax-addon#1]
Hi Florian! We forked this project to customize it to streamline our internal report flow (our team writes dozens of technical code review reports per month in google drive). We'd love to commission you to tweak our fork a little bit, are you available for contract work like this?

Absolutely love this project, by the way. By far the best code highlighter we've used so far and the markdown flow is absolutely friction-less (compared to most add-ons which require highlighting each section).

**Comment by floitsch** [comment]
Thanks :)

Unfortunately I'm too busy at work to accept contract work, but if you let me know which parts you want to change I could probably point you to the code that needs changing (or implement it myself if it's small enough).

**Comment by JorgeAtPaladin** [comment]
Hi floitsch, we've been able to fork and implement the changes ourselves :-) It's a bit specific so probably not worth incorporating upstream. Really appreciate it though and your plugin really makes our lives easier!
