### ISSUE TITLE
Request - support R syntax

### ISSUE THREAD

**Issue by ykr888** [floitsch/syntax-addon#17]
Hi,
Thanks for the great add-on. Is it possible to also add support for the R language syntax?
It seems to exist in codeMirror: [https://github.com/codemirror/codemirror5/tree/master/mode/r](https://github.com/codemirror/codemirror5/tree/master/mode/r)
Thanks.

**Comment by floitsch** [comment]
I will try to add it.
Keep pinging me (maybe once a week), so I don't forget.

**Comment by kevinkrouse** [comment]
And `clojure` as well?

**Comment by ykr888** [comment]
R is all I really need for now. Thanks.

בתאריך יום ה׳, 3 באוג׳ 2023, 19:31, מאת Kevin Krouse ‏<
***@***.***>:

**Comment by floitsch** [comment]
I have added R, Rust and Clojure.
Still need to release the new version, but that should hopefully not take long.

**Comment by floitsch** [comment]
I pushed a new release.
Might take a bit of time if it needs a review from Google, but my work here is done :)

**Comment by ykr888** [comment]
Awesome, thank you so much for the quick response! I checked my google-doc
and it already has the new version, and the R syntax looks great.
