### ISSUE TITLE
Deployment Error

### ISSUE THREAD

**Issue by saimintech** [floitsch/syntax-addon#2]
Hi Florian,

I have run into an issue, I am trying to deploy this as an addon with some custom feature on side menu however, when I deploy the release via clasp which works just fine but when I test the deployment on a test sheet I see the following error on onOpen:

`TypeError: Cannot set property 'defineSimpleMode' of undefined
    at [unknown function](codemirror/third_party/codemirror/addon/mode/simple:14:31)
    at [unknown function](codemirror/third_party/codemirror/addon/mode/simple:10:5)
    at [unknown function](codemirror/third_party/codemirror/addon/mode/simple:11:3)`

Could you advise on this?

**Comment by floitsch** [comment]
My first guess is, that you are not uploading the files in the right order.
If you look at https://github.com/floitsch/syntax-addon/blob/master/codemirror/.clasp.json you can see that the shim must be uploaded first, followed by `codemirror.js` and `clike.js`.

**Comment by saimintech** [comment]
Thank you for quick revert. I have never deployed any script using clasp before and this is my first time. 

So what I understood after reading your comment and also README here (https://github.com/floitsch/syntax-addon/tree/master/codemirror):

1. Deploy the codemirror on a standalone apps script 
2. Deploy the doc version on another script
3. Finally, import the codemirror library inside the doc version script

Does that make sense? Just to let you know that I am trying to pull on the doc version of the syntax library.

**Comment by floitsch** [comment]
That is correct.
However, when deploying with clasp, you also need to make sure that clasp uploads the files in the right order.
You can just take the `.clasp.json` that I have, and replace the `scriptID` with yours. After that, a `clasp push` will upload the files again, but this time in the right order.

**Comment by floitsch** [comment]
Also see https://openbase.com/js/@google/clasp/documentation#filepushorder-optional

**Comment by saimintech** [comment]
Thank you so much for you help. :)

I will revert back with the results.

**Comment by saimintech** [comment]
Hi Florian,

It worked indeed. Thanks again for your support.

Have a nice day!
